### ISSUE TITLE
await is not working :(

### ISSUE THREAD

**Issue by reggi** [TimBeyer/cls-bluebird#18] opened 2018-01-26 18:03 UTC
```
(async () => {
  await new Promise((resolve) => {
    ns.run(() => {
      ns.set('name', 'tom')
      return resolve()
    })
  })
  console.log(ns.get('name'))
})()
```

**Comment by overlookmotel** [comment] 2018-01-26 18:30
Hi @reggi.

cls-bluebird only shims Bluebird. async/await uses native JS promises, so the shim doesn't apply.

Also, as noted in the README "cls-bluebird follows the convention of binding .then() callbacks to the context in which .then() is called". Calling `await` on a bluebird promise implicitly calls `.then()` on the promise. Therefore, in your example, `.then()` is called outside of `ns.run()` and so the `console.log()` line executes outside of the CLS context defined inside the promise constructor.

So, yeah, this is the expected behaviour. And unfortunately there's no way to change this.

We're in a period of transition. `async_hooks` has recently appeared in Node core and a new implementation of CLS will no doubt appear pretty soon which uses it. Bluebird will also need to be patched to support `async_hooks`, and that'll be inside Bluebird itself. So this module cls-bluebird will become deprecated.

But for now, I'm afraid it's a bit of a mess!

**Comment by overlookmotel** [comment] 2018-01-26 18:31
I'm closing this issue. Not because it's not an issue in a sense, but because it's not possible to do anything about it!

**Closed as completed by overlookmotel** 2018-01-26 18:31 UTC

**Comment by reggi** [comment] 2018-01-26 19:41
Thank you for the rich and undeserved explanation @overlookmotel. I see that a lot of work has been put into these issues over the past year, I thank you and applaud your patience.

**Comment by overlookmotel** [comment] 2018-01-26 20:04
@reggi No worries!
